# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='应用名称', max_length=200)),
                ('description', models.CharField(help_text='应用描述', max_length=250)),
                ('level_code', models.CharField(default=1, help_text='层级', max_length=2)),
                ('parent', models.ForeignKey(help_text='父类型', on_delete=django.db.models.deletion.CASCADE, related_name='son_app', to='server_info.AppTypes')),
            ],
        ),
        migrations.RemoveField(
            model_name='serverinfo',
            name='server_id',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='description',
            field=models.CharField(default=None, help_text='服务器描述', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='app_type',
            field=models.ManyToManyField(default=None, null=True, related_name='my_apps', to='server_info.AppTypes'),
        ),
    ]
