# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_info', '0002_auto_20190627_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serveradmin',
            name='server',
        ),
        migrations.AddField(
            model_name='serveradmin',
            name='server',
            field=models.ManyToManyField(related_name='my_user', to='server_info.ServerInfo'),
        ),
    ]
