# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-27 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_info', '0003_auto_20190627_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptypes',
            name='is_active',
            field=models.CharField(default=1, help_text='是否启用', max_length=1),
        ),
    ]
